### ISSUE TITLE
Cargo install failed

### ISSUE THREAD

**Issue by himyyy** [dfinity/icx-proxy#2]
![icx-proxy](https://user-images.githubusercontent.com/13343279/139003608-593932cf-8941-4937-9653-0112bec4caeb.jpg)

**Comment by niteshudhani** [comment]
I also faced the same issue while installing icx-proxy locally. You may need to install pkg-config and openssl to get rid of these errors:
brew install pkg-config
brew install openssl

**Comment by dubecker** [comment]
Had the same issue, found the solution [here](https://github.com/sfackler/rust-openssl/issues/855#issuecomment-450057552).
