### ISSUE TITLE
Calls to `/api` are no longer forwarded to the replica

### ISSUE THREAD

**Issue by paulyoung** [dfinity/icx-proxy#46]
I upgraded `icx-proxy` from e3866f0040d73cda4c5d4092b85af517b11b833f to 7624053a50e1683c48757ee5dacbb454921e39ef and now the initial call to `/api/v2/status` returns the HTML page of my asset canister, and a CBOR decoder tries to decode that and throws an error.

I downgraded back to e3866f0040d73cda4c5d4092b85af517b11b833f API calls were forwarded again.

Is there some new flag I need to pass to get the old behavior? I couldn't see anything obvious in the help text.

**Comment by nomeata** [comment]
This is intentional - at least for secure domains such uncertified “holes” make your users attackable by a malicious replica.

You should not use the canister domain for IC requests, but some generic domain (is it simply `ic0.app`? I don't remember)

**Comment by paulyoung** [comment]
This is all abstracted away from me by `agent-js`; I’m using `createActor` as shown in the README: https://github.com/dfinity/agent-js/blob/main/packages/auth-client/README.md#in-the-browser

By the way, I’m only using `icx-proxy` locally; I have a wrapper script that reads the relevant canister’s ID and then starts `icx-proxy` with the `--dns-alias` flag, since it’s inconvenient for a certain client I’m targeting to have to update the canister ID if/when it changes.

**Comment by nomeata** [comment]
Ah, so maybe (just guessing) the agent has logic for picking the right gateway domain in production, but not locally. Hmmm.

**Comment by paulyoung** [comment]
I think calls are made relative to the current domain, so if I do `--dns-alias myproject.local:<canister id of myproject_assets>` then browse to http://myproject.local in a Chromium browser (I use Brave) it serves up the front end and calls http://myproject.local/api/v2/status

**Comment by nomeata** [comment]
Right, that is the old behaviour that used to work, until the proxing of `/api` was removed. For production, the agent takes care of it since https://github.com/dfinity/agent-js/pull/516 I think…

**Comment by paulyoung** [comment]
I’ll try upgrading `agent-js`

**Comment by nomeata** [comment]
That change won’t help you in the local use-case, I don’t know if any others changes there have. But worth trying, of course.

**Comment by paulyoung** [comment]
Based on [this post](https://forum.dfinity.org/t/urgent-application-not-accessible-via-browser-on-subnet-pjljw-kztyl-46ud4-ofrj6-nzkhm-3n4nt-wi3jt-ypmav-ijqkt-gjf66-uae/14566/6?u=paulyoung) by @Daniel-Bloom-dfinity I think I need to set something like `isLocal ? "127.0.0.1:8000" : "ic0.app"` (the local replica runs on port `8000`)

@ninegua also shared something in [this post](https://forum.dfinity.org/t/custom-domains-for-ic0-app-community-consideration/6162/58?u=paulyoung) about using `ic0.app`

Perhaps seeing `<canister id>.ic0.app` all the time has confused people. I think that's what confused me.

**Comment by paulyoung** [comment]
Setting the host as described above appears to be working as intended. Thanks for the help!

**Comment by paulyoung** [comment]
In addition to the above I had set the host to `127.0.0.1:8080` when running my local dev server for iterating on the front end (I'm using `esbuild` on port `8080` but other people may be using something like webpack dev server on a different port)

I think not setting the `host` or setting it to `undefined` has the same effect but I have an abstract over this and didn't want to may it optional.

I still needed to forward `/api` using some proxy middleware due to CORS.

**Comment by paulyoung** [comment]
I think the simple solution to the above is to use `host: window.location.host`

**Comment by paulyoung** [comment]
Ah, no, that's the default and that includes the subdomain.
